### ISSUE TITLE
Errors when building with css.extract = false

### ISSUE THREAD

**Issue by gerwinov** [adamwathan/vue-cli3-tailwind#1]
Hi Adam,

Thanks for creating this repo, it gives a nice starting point to use Tailwind with the Vue-CLI. 

The project I'm working on now has a very similar structure as this example repo. I'm building my project as a library, so I would like to avoid the CSS being extracted when building. The Vue-CLI documentation provides an option for this [here](https://cli.vuejs.org/config/#css-extract). 

I tried using this within your example repo by adding a file called `vue.config.js` in the root. The file looks like this:
```
module.exports = {
  css: {
    extract: false
  }
}
```

When I now run `npm run build` the following errors appear:
```
* -!../node_modules/css-loader/index.js??ref--6-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--6-oneOf-1-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!./tailwindcss/components in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--6-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=css&
* -!../node_modules/css-loader/index.js??ref--6-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--6-oneOf-1-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!./tailwindcss/preflight in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--6-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=css&
* -!../node_modules/css-loader/index.js??ref--6-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--6-oneOf-1-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!./tailwindcss/utilities in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--6-oneOf-1-2!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=css&

To install them, you can run: npm install --save -!../node_modules/css-loader/index.js??ref--6-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--6-oneOf-1-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!./tailwindcss/components -!../node_modules/css-loader/index.js??ref--6-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--6-oneOf-1-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!./tailwindcss/preflight -!../node_modules/css-loader/index.js??ref--6-oneOf-1-1!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/lib/index.js??ref--6-oneOf-1-2!../node_modules/cache-loader/dist/cjs.js??ref--0-0!./tailwindcss/utilities
```

Building is successful when I don't include the `vue.config.js` file and also when I run `npm run serve` (which also doesn't extract css).

Do you have an idea what might cause this and how to resolve it?

Thanks in advance!

Best regards,
Gerwin

**Comment by adamwathan** [comment]
I'm not seeing errors but I am seeing that PostCSS is just not being processed at all when that option is set, so I've reported it as a bug with a reproduction: https://github.com/vuejs/vue-cli/issues/2451

**Comment by gerwinov** [comment]
Thanks for looking in to this! I'll follow the discussion in the issue you created.

**Comment by doublemarked** [comment]
I'm experiencing this same problem with 3.0.1, after upgrading from one of the late RCs. It only happens for .vue files, not for .css files.

I've debugged it a bit. It appears to have been introduced with the following commit,
   https://github.com/vuejs/vue-cli/commit/a2c767efc4221b6afbaa33a065a5560b4e44debc

The problem with that commit is that it adds `nanocss` to the postcss config, and later when `postcss-loader` loads up, it already has a config object passed in so it doesn't load any of the config (including plugins etc) from package.json / postcssrc, etc. See here: https://github.com/postcss/postcss-loader/blob/master/src/index.js#L36-L52

Not sure what the right fix is to this, but looking forward to figuring out how to fix our build! :)
